import { Link, useParams } from 'react-router-dom'
import { articles, categories, categoryById, categoryPath, articlePath, formatDate, relatedArticles, type Article } from './data'

function BlogHeader() {
  return <header className="blog-header"><div className="blog-container blog-header-inner"><Link className="blog-brand" to="/">toprepet<span> / блог</span></Link><nav aria-label="Блог"><Link to="/blog/">Статьи</Link><Link to="/">Главная</Link><a className="blog-button" href="/lessons/">Найти репетитора</a></nav></div></header>
}
function BlogFooter() { return <footer className="blog-footer blog-container"><Link to="/">TopRepet</Link><Link to="/blog/">Блог</Link><Link to="/contact/">Контакты</Link></footer> }
function Card({ article }: { article: Article }) { const category = categoryById(article.category_id); return <Link className="blog-card" to={articlePath(article)}>{article.cover_image_url && <img src={article.cover_image_url} alt={article.cover_image_alt || ''} loading="lazy" />}<div className="blog-card-content">{category && <span className="blog-eyebrow">{category.name}</span>}<h3>{article.title}</h3><p>{article.excerpt}</p><small>{formatDate(article.published_at)}</small></div></Link> }
function BlogHome() { const roots = categories.filter(item => !item.parent_id && articles.some(article => article.category_id === item.id || categories.some(child => child.parent_id === item.id && child.id === article.category_id))); return <><section className="blog-intro"><p className="blog-eyebrow">Журнал TopRepet</p><h1>Статьи об учёбе и подготовке к экзаменам</h1><p>Полезные объяснения, советы и разборы от редакции TopRepet.</p></section>{roots.length > 0 && <section className="blog-section"><h2>Темы</h2><div className="blog-chips">{roots.map(category => <Link to={categoryPath(category)} key={category.id}>{category.name}</Link>)}</div></section>}<section className="blog-section"><h2>Новые статьи</h2>{articles.length ? <div className="blog-grid">{articles.map(article => <Card article={article} key={article.id} />)}</div> : <p>Статьи скоро появятся.</p>}</section></> }
function RubricPage() { const { '*': slugPath } = useParams(); const category = categories.find(item => categoryPath(item) === `/blog/rubrics/${slugPath}/`); if (!category) return <NotFound />; const descendants = new Set([category.id]); for (let i = 0; i < 8; i++) categories.filter(item => item.parent_id && descendants.has(item.parent_id)).forEach(item => descendants.add(item.id)); const selected = articles.filter(item => descendants.has(item.category_id)); return <><nav className="blog-breadcrumb"><Link to="/blog/">Блог</Link> / {category.name}</nav><section className="blog-intro"><h1>{category.name}</h1>{category.description && <p>{category.description}</p>}</section><div className="blog-chips">{categories.filter(item => item.parent_id === category.id).map(item => <Link to={categoryPath(item)} key={item.id}>{item.name}</Link>)}</div><section className="blog-section"><h2>Статьи</h2><div className="blog-grid">{selected.map(article => <Card article={article} key={article.id} />)}</div></section></> }
function ArticlePage() { const { slug } = useParams(); const article = articles.find(item => item.slug === slug); if (!article) return <NotFound />; const category = categoryById(article.category_id); const related = relatedArticles(article); const cta = new URL('https://toprepet.ru/free-intro/'); cta.searchParams.set('utm_source','blog'); cta.searchParams.set('utm_medium','referral'); cta.searchParams.set('utm_campaign','article_cta'); cta.searchParams.set('utm_content',article.slug); return <article className="blog-article"><nav className="blog-breadcrumb"><Link to="/blog/">Блог</Link>{category && <> / <Link to={categoryPath(category)}>{category.name}</Link></>}</nav><header><h1>{article.title}</h1>{article.excerpt && <p className="blog-lead">{article.excerpt}</p>}<p className="blog-meta">{article.author_name} · {formatDate(article.published_at)}</p></header>{article.cover_image_url && <figure className="blog-cover"><img src={article.cover_image_url} alt={article.cover_image_alt || ''} /></figure>}<div className="article-body" dangerouslySetInnerHTML={{ __html: article.content_html }} /><aside className="blog-cta"><h2>Нужна помощь с этой темой?</h2><p>Подберите преподавателя TopRepet под свою цель. Первое знакомство бесплатно.</p><a className="blog-button" href={cta.href}>Подобрать репетитора</a></aside>{related.length > 0 && <section className="blog-section"><h2>Читайте также</h2><div className="blog-grid">{related.map(item => <Card article={item} key={item.id} />)}</div></section>}</article> }
function NotFound() { return <section className="blog-intro"><h1>Страница не найдена</h1><Link to="/blog/">Вернуться в блог</Link></section> }
export function PublicBlog({ page }: { page: 'home' | 'rubric' | 'article' }) { return <div className="blog-root"><BlogHeader /><main className="blog-container">{page === 'home' ? <BlogHome /> : page === 'rubric' ? <RubricPage /> : <ArticlePage />}</main><BlogFooter /></div> }

