import { BarChart3, BookOpen, Clock3, Layers3 } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { Header as MainHeader } from '../widgets/header/header'
import { Footer as MainFooter } from '../widgets/footer/footer'
import { articles, categories, categoryById, categoryPath, articlePath, formatDate, relatedArticles, type Article, type Category } from './data'

function hasPublished(category: Category) { return articles.some(article => { let current = categoryById(article.category_id); while (current) { if (current.id === category.id) return true; current = categoryById(current.parent_id || '') } return false }) }
function readTime(article: Article) { return `${Math.max(1, Math.ceil(article.content_html.replace(/<[^>]*>/g, ' ').trim().split(/\s+/).length / 180))} мин чтения` }

function Card({ article }: { article: Article }) { const category = categoryById(article.category_id); return <article className="article-card"><Link to={articlePath(article)} aria-label={`Читать: ${article.title}`} className={`article-card-media ${article.cover_image_url ? '' : 'article-card-placeholder'}`}>{article.cover_image_url ? <img src={article.cover_image_url} alt={article.cover_image_alt || article.title} loading="lazy"/> : <BookOpen size={40} strokeWidth={1.4}/>}</Link><div className="article-card-body"><div className="article-card-byline">{category && <Link to={categoryPath(category)} className="article-card-category">{category.name}</Link>}<span>{article.author_name}</span></div><h3><Link to={articlePath(article)}>{article.title}</Link></h3><p className="line-clamp-2">{article.excerpt}</p><div className="article-card-meta"><time dateTime={article.published_at || undefined}>{formatDate(article.published_at)}</time><span aria-hidden="true">·</span><span>{article.view_count} просмотров</span><span aria-hidden="true">·</span><span>{readTime(article)}</span></div></div></article> }
function Empty({ popular = false }: { popular?: boolean }) { const Icon = popular ? BarChart3 : BookOpen; return <div className={`empty-state ${popular ? 'empty-state-compact' : ''}`}><Icon aria-hidden="true"/><div><strong>{popular ? 'Здесь появятся популярные статьи' : 'Пока нет опубликованных статей'}</strong><p>{popular ? 'Рейтинг сформируется по просмотрам.' : 'Новые материалы появятся в этом разделе.'}</p></div></div> }

function Home() { const roots = categories.filter(category => !category.parent_id && hasPublished(category)); const popular = [...articles].sort((a,b) => b.view_count - a.view_count).slice(0,4); return <main><section className="page-shell blog-intro"><h1>Учёба без лишней сложности</h1><p>Понятные разборы школьных тем и материалы для подготовки к ОГЭ и ЕГЭ.</p><div className="intro-actions"><a className="button-primary" href="#fresh">Читать материалы</a><a className="button-outline" href="#directions">Выбрать направление</a></div></section><section id="directions" className="page-shell section-block directions-section" aria-labelledby="directions-title"><div className="section-heading-simple"><Layers3 aria-hidden="true"/><h2 id="directions-title" className="section-title">Направления</h2></div>{roots.length ? <nav className="direction-grid" aria-label="Направления блога">{roots.map(category => <Link key={category.id} to={categoryPath(category)} className="direction-card"><span>{category.name}</span><small>{category.description || 'Материалы и полезные разборы'}</small></Link>)}</nav> : <div className="empty-state"><BookOpen aria-hidden="true"/><div><strong>Рубрики скоро появятся</strong><p>Мы готовим первые направления и материалы.</p></div></div>}</section><div className="page-shell home-feed-grid"><section id="fresh" className="section-block home-feed-main" aria-labelledby="fresh-title"><div className="section-heading-simple"><Clock3 aria-hidden="true"/><h2 id="fresh-title" className="section-title">Свежее</h2></div>{articles.length ? <div className="article-list">{articles.slice(0,8).map(article => <Card key={article.id} article={article}/>)}</div> : <Empty/>}</section><aside id="popular" className="section-block popular-section" aria-labelledby="popular-title"><div className="section-heading-simple"><BarChart3 aria-hidden="true"/><h2 id="popular-title" className="section-title">Популярное</h2></div>{popular.length ? <ol className="popular-list">{popular.map((article,index) => <li key={article.id}><span>{String(index+1).padStart(2,'0')}</span><Link to={articlePath(article)}>{article.title}</Link></li>)}</ol> : <Empty popular/>}</aside></div><section className="page-shell blog-cta"><div><h2>Нужна помощь с учёбой?</h2><p>Подберите репетитора под свою цель на основном сайте.</p></div><a className="button-primary" href="https://toprepet.ru/lessons/">Выбрать репетитора</a></section></main> }

function Breadcrumbs({ category, articleTitle }: { category?: Category; articleTitle?: string }) { const branch: Category[] = []; let current = category; while(current && branch.length < 8) { branch.unshift(current); current = categoryById(current.parent_id || '') } return <nav className="article-breadcrumbs" aria-label="Навигационная цепочка"><Link to="/blog/">Блог</Link>{branch.map(item => <span key={item.id}> / <Link to={categoryPath(item)}>{item.name}</Link></span>)}{articleTitle && <span> / {articleTitle}</span>}</nav> }
function Rubric() { const { '*': slugPath } = useParams(); const category = categories.find(item => categoryPath(item) === `/blog/rubrics/${slugPath}/`); if (!category || !hasPublished(category)) return <NotFound/>; const descendants = new Set([category.id]); for(let i=0;i<8;i++) categories.filter(item => item.parent_id && descendants.has(item.parent_id)).forEach(item => descendants.add(item.id)); const selected = articles.filter(item => descendants.has(item.category_id)); const children = categories.filter(item => item.parent_id === category.id && hasPublished(item)); return <main className="page-shell rubric-page"><Breadcrumbs category={category}/><header className="rubric-heading"><h1>{category.name}</h1>{category.description && <p>{category.description}</p>}</header>{children.length > 0 && <nav className="rubric-nav rubric-children" aria-label="Разделы рубрики"><span>Разделы</span><div className="rubric-links">{children.map(item => <Link key={item.id} to={categoryPath(item)}>{item.name}</Link>)}</div></nav>}<section className="section-block"><h2 className="section-title">Статьи</h2><div className="article-list">{selected.map(article => <Card key={article.id} article={article}/>)}</div></section></main> }
function ArticleMarkup({ article }: { article: Article }) {
  const url = `https://toprepet.ru${articlePath(article)}`;
  const category = categoryById(article.category_id);
  const schema = {
    '@context': 'https://schema.org', '@type': 'BlogPosting', '@id': `${url}#article-content`,
    url, headline: article.title, description: article.excerpt,
    text: article.content_html.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim(),
    author: { '@type': 'Person', name: article.author_name },
    publisher: { '@type': 'Organization', name: 'TopRepet', url: 'https://toprepet.ru/' },
    articleSection: category?.name, datePublished: article.published_at || undefined,
    dateModified: article.modified_at || article.updated_at,
    image: article.cover_image_url || undefined, inLanguage: 'ru-RU',
  };
  return <script type="application/ld+json">{JSON.stringify(schema).replace(/</g, '\\u003c')}</script>;
}

function ArticlePage() { const { slug } = useParams(); const article = articles.find(item => item.slug === slug); if (!article) return <NotFound/>; const category = categoryById(article.category_id); const related = relatedArticles(article); const cta = new URL('https://toprepet.ru/free-intro/'); return <main className="page-shell article-page"><div className="article-shell"><Breadcrumbs category={category} articleTitle={article.title}/><article id="article-content"><ArticleMarkup article={article}/><header className="article-header">{category && <Link className="article-category" to={categoryPath(category)}>{category.name}</Link>}<h1>{article.title}</h1>{article.excerpt && <p className="article-lead">{article.excerpt}</p>}<div className="article-details"><div className="article-details-text"><strong>{article.author_name}</strong>{article.published_at && <time dateTime={article.published_at}>Опубликовано {formatDate(article.published_at)}</time>}{article.modified_at && <time dateTime={article.modified_at}>Обновлено {formatDate(article.modified_at)}</time>}<span>{readTime(article)}</span><span>{article.view_count} просмотров</span></div></div></header>{article.cover_image_url && <figure className="article-cover"><img src={article.cover_image_url} alt={article.cover_image_alt || article.title}/></figure>}<div className="article-content-layout"><section aria-label="Текст статьи" className="article-body" dangerouslySetInnerHTML={{__html:article.content_html}}/></div></article><aside className="article-cta"><div><h2>Нужна помощь с этой темой?</h2><p>Подберите преподавателя TopRepet под свою цель. Первое знакомство бесплатно.</p></div><a className="button-primary" href={cta.href}>Подобрать репетитора</a></aside>{related.length > 0 && <section className="section-block related-section"><h2 className="section-title">Читайте также</h2><div className="article-list">{related.map(item => <Card key={item.id} article={item}/>)}</div></section>}</div></main> }
function NotFound() { return <main className="page-shell blog-intro"><h1>Страница не найдена</h1><Link to="/blog/">Вернуться в блог</Link></main> }
export function PublicBlog({ page }: { page: 'home' | 'rubric' | 'article' }) { return <div className="blog-root"><MainHeader/>{page === 'home' ? <Home/> : page === 'rubric' ? <Rubric/> : <ArticlePage/>}<MainFooter/></div> }
