'use client';
import { useState } from 'react';
import { ArrowUpRight, ArrowRight, Code2, Check, Menu, X, Monitor, MessageCircle, MoveUpRight } from 'lucide-react';
import RequestForm from './request-form';

export default function Home() {
  const [menu, setMenu] = useState(false);
  const [direction, setDirection] = useState('ОГЭ · Информатика');
  function choose(value: string) { setDirection(value); }
  return <>
    <a className="skip-link" href="#main">Перейти к содержимому</a>
    <header className="header"><div className="container nav-wrap">
      <a href="#" className="brand" aria-label="TopRepet — на главную"><span className="brand-symbol"><MoveUpRight size={24}/></span>toprepet<span className="brand-dot">.</span></a>
      <nav aria-label="Основная навигация" id="main-nav" className={menu ? 'nav is-open' : 'nav'}>{[['Направления','directions'],['Репетиторы','tutors'],['Как это работает','process'],['Стоимость','price']].map(([name,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{name}</a>)}</nav>
      <a className="button nav-cta" href="#request">Записаться <ArrowUpRight size={17}/></a>
      <button className="menu-toggle" aria-label={menu?'Закрыть меню':'Открыть меню'} aria-controls="main-nav" aria-expanded={menu} onClick={()=>setMenu(!menu)} onKeyDown={e=>{if(e.key==='Escape')setMenu(false)}}>{menu?<X/>:<Menu/>}</button>
    </div></header>
    <main id="main">
      <section className="container hero">
        <div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> ЧАСТНЫЕ РЕПЕТИТОРЫ · ОНЛАЙН</div>
        <h1>Сложное станет<br/><span className="highlight">понятным.</span></h1>
        <p className="hero-description">От первого «почему?» до уверенного решения.<br className="desktop-break"/> Поможем разобраться в учёбе и подготовиться к экзаменам — в своём темпе, с поддержкой репетитора.</p>
        <div className="hero-price"><strong>1 200 ₽</strong><span>за 60 минут<br/>по любому направлению</span></div>
        <a href="#request" className="button primary">Найти своего репетитора <ArrowUpRight size={20}/></a>
        <div className="hero-note"><span className="check-circle"><Check size={13}/></span> Первое короткое знакомство — бесплатно</div></div>
        <div className="hero-visual"><img src="/images/hero.webp" width="1448" height="1086" alt="Ноутбук с кодом Python на синем рабочем столе" fetchPriority="high"/><div className="visual-top"><span className="white-dot"/> УЧИТЬСЯ МОЖНО СПОКОЙНО</div><div className="visual-bottom"><span className="code-mark"><Code2 size={25}/></span><div><small>ФОКУС НА СТАРТЕ</small><strong>Информатика<br/>ОГЭ и ЕГЭ</strong></div><a href="#informatics" aria-label="Подготовка по информатике"><ArrowUpRight/></a></div></div>
      </section>
      <div className="container benefit-strip"><span><Monitor size={19}/> Занятия один на один</span><span><MessageCircle size={19}/> Можно задавать любые вопросы</span><span><Check size={19}/> От понимания к практике</span></div>
      <section className="container section" id="directions"><div className="section-heading"><div><div className="eyebrow">НАПРАВЛЕНИЯ</div><h2>На каждом этапе —<br/>своя поддержка</h2></div><p>Начать с основ, разобраться в теме<br/>или собраться перед экзаменом.</p></div><div className="direction-grid">{['Дошкольники','1–4 классы','5–8 классы','ОГЭ','ЕГЭ'].map((t,i)=><a className={'direction-card '+(i>2?'exam-direction':'')} href={i>2?'#informatics':'#request'} onClick={()=>choose(i>2?t+' · Информатика':t)} key={t}><span className="card-index">0{i+1}</span><h3>{t}</h3><p>{['Подготовка к школе. Чтение, счёт и знакомство с учёбой.','Первые самостоятельные шаги. Базовые предметы и домашние задания.','Школьная программа, отдельные предметы и разбор сложных тем.','Подготовка к экзаменам в 9 классе. Начинаем с информатики.','Подготовка к экзаменам в 11 классе. Начинаем с информатики.'][i]}</p><span className="card-arrow"><ArrowUpRight size={20}/></span></a>)}</div></section>
      <section id="informatics" className="container section"><div className="informatics-panel"><div className="informatics-intro"><div className="eyebrow">ГЛАВНОЕ НАПРАВЛЕНИЕ</div><h2>Информатика.<br/>От «не понимаю»<br/>до «я разобрался».</h2><p>Логика, алгоритмы и код складываются в систему, когда есть кому объяснить и с кем потренироваться.</p><div className="code-decoration" aria-hidden="true">&lt;/&gt;</div></div><div className="exam-grid">{[['ОГЭ','09','Укрепляем основу','Разбираем логику и кодирование, работаем с таблицами и алгоритмами. Учимся понимать условие и проверять решение.',['База','Практика','Разбор ошибок']],['ЕГЭ','11','Идём глубже','Тренируем программирование, анализ данных и решение задач. Подбираем сложность под текущий уровень и цель.',['Python','Алгоритмы','Задачи']]].map(([exam,num,title,desc,tags])=><article key={exam as string}><span>{num} / {exam}</span><h3>{title}</h3><p>{desc}</p><div className="tags">{(tags as string[]).map(t=><span key={t}>{t}</span>)}</div><a href="#request" className="exam-link" onClick={()=>choose(exam+' · Информатика')}>Готовиться к {exam} <ArrowUpRight size={20}/></a></article>)}</div></div></section>
      <section className="container section" id="tutors"><div className="section-heading"><div><div className="eyebrow">РЕПЕТИТОРЫ</div><h2>Важен человек,<br/>с которым понятно</h2></div><p>На знакомстве можно задать вопросы<br/>и понять, комфортно ли заниматься вместе.</p></div><p className="placeholder-note">Анкеты готовятся. Ниже — места для проверенных данных и фотографий преподавателей.</p><div className="tutor-grid">{['Информатика · ОГЭ','Информатика · ЕГЭ','Школьные предметы'].map((subject,i)=><article className="tutor-card" key={subject}><div className={'portrait-placeholder portrait-'+i}><span>[ Фотография преподавателя ]</span><span className="profile-status">Анкета скоро</span></div><div className="tutor-info"><div className="eyebrow">{subject}</div><h3>[Имя преподавателя]</h3><p>[Здесь появятся сведения об опыте, предметах и подходе к занятиям.]</p></div></article>)}</div></section>
      <section className="container section" id="process"><div className="eyebrow">КАК ПРОХОДЯТ ЗАНЯТИЯ</div><h2>Всё начинается<br/>с простого знакомства</h2><div className="steps">{[['Расскажите о задаче','Оставьте заявку: класс, предмет и то, с чем нужна помощь.'],['Познакомьтесь','Коротко пообщайтесь с преподавателем бесплатно. Обсудите цель и удобное время.'],['Занимайтесь в своём темпе','Разбирайте темы один на один онлайн, решайте задачи и задавайте вопросы.'],['Закрепляйте понимание','Возвращайтесь к сложным моментам и обсуждайте, чему уделить внимание дальше.']].map(([t,p],i)=><article key={t}><div className="step-number">0{i+1}<ArrowRight size={18}/></div><h3>{t}</h3><p>{p}</p></article>)}</div></section>
      <section className="container section" id="price"><div className="pricing"><div><div className="eyebrow">ЕДИНАЯ СТОИМОСТЬ</div><h2>Один на один.<br/>По понятной цене.</h2><p>Для любого возраста, предмета и цели.<br/>От подготовки к школе до ЕГЭ.</p></div><div className="price-right"><div className="big-price">1 200 <span>₽</span></div><p>одно занятие · 60 минут</p><div className="price-perks"><span><Check size={18}/> Индивидуальное внимание</span><span><Check size={18}/> Разбор тем и практика</span><span><Check size={18}/> Бесплатное короткое знакомство</span></div><a href="#request" className="button dark-button">Записаться на знакомство <ArrowUpRight size={20}/></a></div></div></section>
      <section className="container section faq-section" id="faq"><div><div className="eyebrow">ЕСТЬ ВОПРОСЫ?</div><h2>Давайте<br/>разберёмся</h2></div><div className="faq-list">{[['TopRepet — это онлайн-школа?','TopRepet — сервис частных репетиторов. Индивидуальные занятия проводит выбранный преподаватель; содержание, расписание и условия вы обсуждаете с ним.'],['Что входит в бесплатное знакомство?','Короткий разговор с преподавателем: знакомитесь, рассказываете о задаче, обсуждаете формат и расписание. Это знакомство, а не полноценное занятие на 60 минут. Точную длительность согласуете заранее.'],['Можно ли прийти с домашним заданием?','Да. Репетитор поможет понять условие, разобрать способ решения и потренироваться. Задача занятия — чтобы ученик смог применять этот способ самостоятельно.'],['Как проходят онлайн-занятия?','Для занятия понадобится устройство с интернетом, камерой и микрофоном. Площадку для видеосвязи и материалы согласуете с преподавателем на знакомстве.'],['Что делать, если нужно перенести занятие?','Предупредите преподавателя заранее. Сроки уведомления, переносы, отмены и порядок оплаты обсудите с ним до начала занятий.'],['Можно ли начать с нуля?','Можно начать с текущего уровня. На первых встречах определите пробелы и последовательность тем. Темп и план зависят от исходных знаний, времени на практику и даты экзамена.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
      <section className="container section" id="request"><div className="request-panel"><div><div className="eyebrow">ПЕРВЫЙ ШАГ</div><h2>Давайте начнём<br/>с «привет»</h2><p>Расскажите, с чем нужна помощь.<br/>Начнём с бесплатного знакомства<br/>и обсудим подходящий план занятий.</p><div className="request-note"><MessageCircle/><span>Без обязательств.<br/>Сначала познакомимся.</span></div></div><RequestForm direction={direction} onDirectionChange={setDirection}/></div></section>
    </main><footer className="container footer" id="contacts"><div className="footer-top"><div><a className="brand" href="#"><span className="brand-symbol"><MoveUpRight size={24}/></span>toprepet.</a><p>Частные репетиторы.<br/>Понятная учёба.</p></div><div><h3>Связаться с нами</h3><p>[Телефон будет добавлен]<br/>[Электронная почта будет добавлена]</p></div><div><h3>Мессенджеры</h3><p>Telegram · [ссылка будет добавлена]<br/>WhatsApp · [ссылка будет добавлена]</p></div></div><div className="footer-bottom"><span>© 2026 TopRepet</span><span>Сервис частных репетиторов</span><a href="#request">Начать знакомство <ArrowUpRight size={15}/></a></div></footer>
  </>;
}

